### ISSUE TITLE
Feedback for Table Display with SAP Help Docs

### ISSUE THREAD

**Issue by freetimecoder3** [SAP-docs/btp-cloud-platform#100]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/cc1c676b43904066abb2a4838cbd0c37.html

**Need:** Kindly display tables such that the table headers are shown during scrolling, when the table contents are being seen.

**Background:**
Whenever tables are displayed in HTML page, there is almost always the need to scroll down to read content. And most times what does each column mean different and this relation is lost and needs again a scroll up to check and then a scroll down back to content.  This gets tiresome.  Specially when reading a help document/page for the first time !!!

Hope this can be done ASAP.

You can reach me at I353040 for more info.

Cheers.

BR,
Ganesh S

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MichaelPShea** [comment]
@freetimecoder3 , thanks very much for your feedback. If the table had consisted of more than two rows, I would have agreed with you. Still, given the length of the content in the table it does make it harder to read. You can widen the display by clicking on the double chevrons at the top of the screen >> to hide the navigation and comments sections. While we haven't implemented this suggestion, please continue to provide feedback. It is really appreciated.

**Comment by freetimecoder3** [comment]
Hi @MichaelPShea ,  Monitor sizes have improved, possibly if i use a 38 inch External monitor, i whole heartedly agree with you.   I almost always use laptop screen that has 14 inch monitor OR a tablet that has 10 inch screen.   And it is not possible to read even with Chevron expanded.  Hence the request.

**Comment by MichaelPShea** [comment]
@freetimecoder3, that's a very good point. Thanks for sharing your experience. Unfortunately the central infrastructure we work on doesn't enable me to turn on scrolling headers for all types of tables. There is one table format I could change to, but that would add content to the table headings, making them more unwieldy. Since the table is only two rows, I can only ask for your forgiveness and hold out the hope that in the future only feature set B will be available and you won't have to scroll between the feature sets any more.
