### ISSUE TITLE
Feedback for "Security Events Logged by the CF Services"

### ISSUE THREAD

**Issue by ajmaradiaga** [SAP-docs/btp-cloud-platform#121]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/84acdc91c60c4f32b7c06cdbc442fdef.html?locale=en-US

The SAP Build Workzone Standard edition (SAP Launchpad) is not included in the table and I believe that it also logs audit related events.... See Launchpad documentation here: https://help.sap.com/docs/Launchpad_Service/8c8e1958338140699bd4811b37b82ece/d7b1a89c9a0f46bd9b1e2b6ca70add66.html?locale=en-US&q=Auditing#data-protection-and-privacy

**Comment by petiansap** [comment]
Dear ajmaradiaga, 
Thank you for your feedback!
The reason Launchpad and some other services, which also log audit related events, are not included in the table is because they have not created the required Auditing and Logging Information page for their service. There are jira issues created for each service. 
I reminded the colleagues from Launchpad to complete this task. I'll update the table as soon as the page is available.
Best wishes,
Petia

**Comment by nikolasimeonov77** [comment]
I close this issue as Petia already responded that the problem is addessed and the documentation is to be updated within next 2 weeks.
