### ISSUE TITLE
Feedback for "Parameters and Properties"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#129]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/490c8f71e2b74bc0a59302cada66117c.html

> Each tool publishes a list of system parameters

What is a 'tool'? Where do we find all system parameters per tool?
Please complete the list of system/generic/read-only parameters.

As you can see, I'm not sure what to call them... 😉
I must say that I'm not a fan of the term 'parameter' in this context... 
IMO, the term `deployer variable` would be more meaningful.

Some "system parameters" that are missing from the documentation here:
- platform
- default-uri
- default-url
- default-host
- default-domain
- default-url
- default-port
- default-xsappname
- protocol
- app-name
- timestamp

There are probably others, so it would be useful to get the full list in the documentation.

Related: https://github.com/SAP/cloud-mta-build-tool/issues/1005

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by lilyanarangelova** [comment]
Hi,
Thank you for your feedback! I'll forward it to my colleague who is responsible for this documentation.

Best regards,
Lilyana

**Comment by boyan-velinov** [comment]
@piejanssens  Thanks for the feedback!

The page [Parameters and Properties](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/490c8f71e2b74bc0a59302cada66117c.html) can be improved by making it more focused on MTA deployment in BTP Cloud Foundry environment. We need to remove all abstract statements like referred one:

> Each tool publishes a list of system parameters..

Other points for improvements:

- Explain that system and read-only parameters are the same
- Explain that this page and Global Parameters table inside are for generic parameters on all levels, which inlcudes top-level parameters; module level parameters and resource level parameters; if a parameter is relevant for apps the parameter is documented on [MTA modules page](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters)

I agree that Parameter and Properties are not clear thems, but they came from MTA specificiation:
https://www.sap.com/documents/2021/09/66d96898-fa7d-0010-bca6-c68f7e60039b.html

The MTA specification have various implementation on MTA deployment side for different environments, like BTP Cloud Foundry, BTP Neo and HANA XSA. It has implementations on MTA design time like MTA build tool, WebIDE Full Stack.
MTA specification is used also from other tools that are not included in MTA parsing and processing.
I am saying all of this because we will keep the term as it is in order to comply with MTA specification and all other related tools/scenarios.

For sure, we will think about of making it more clear for what Parameters are used.

As a reference for the mentioned parameters:

- platform -> does not exist in MTA deployment at BTP Cloud Foundry environment
- default-uri -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters
- default-url -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters
- default-host -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters
- default-domain -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters
- default-url -> duplicated
- default-port -> does not exist in MTA deployment at BTP Cloud Foundry environment
- default-xsappname -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/9e34487b1a8643fb9a93ae6c4894f015.html#resource-specific-parameters
- protocol -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters
- app-name -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters
- timestamp -> https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/177d34d45e3d4fd99f4eeeffc5814cf1.html#module-specific-parameters

**Comment by lilyanarangelova** [comment]
The documentation has been updated
