### ISSUE TITLE
Why booster is only intended to create development systems.

### ISSUE THREAD

**Issue by lconstantinosap** [SAP-docs/btp-cloud-platform#176]
### Issue description

Hi all,
Why booster is only intended to create development systems.
because it needs more steps to complete the configuration in Test Prd environments?
Or with booster users are crated with dev roles and its not intended in Test Prd environment's? 
Regards

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Using a Booster to Automate the Setup of the ABAP Environment (Optional)

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/btp/sap-business-technology-platform/using-booster-to-automate-setup-of-abap-environment-optional

**Comment by nikolasimeonov77** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by sarahbaczyk** [comment]
Hello and thank you for your patience.
We have received the information that a booster for test/prod systems has not been developed so far.The checkmark "Development System" is put in automatically because of that - it is not connected to the user role.
One could theoretically use the booster for test/prod systems as well, if development is strictly left out. Though the latter is more error-prone than just manually creating a test/prod environment for that matter.

**Comment by nikolasimeonov77** [comment]
Hi @lconstantinosap,
I hope that the above answer is sufficient for you? I'll close the item for now, but if you need further information or requests, please feel free to reopen it.

Thanks for your collaboration!

Nikola

**Comment by lconstantinosap** [comment]
Its clear now, thanks for the clarification
