### ISSUE TITLE
Feedback for "Register the Assertion Consumer Service for Every Extension Application in SAP SuccessFactors"

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-cloud-platform#3]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/ebc8341367a64fe3a5b187a4e2440608.html?locale=en-US

Why is this required? 
What does this do?

**Comment by ekaterina-mitova** [comment]
Hello @piejanssens , 

Thank you for your question! Yes, you need to register an ACS for every extension application in SAP SuccessFactors because this is part of the SSO setup. Note that this procedure is required only if you use SAP BTP, Cloud Foundry environment. 
See also [Configure Single-Sign On Between a Subaccount in SAP BTP and SAP SuccessFactors](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/64da613776814c3f8d899686dee558ca.html?version=Cloud).

Best regards, 
Ekaterina

**Comment by piejanssens** [comment]
Hello @ekaterina-mitova,

Thanks for your reply. I am actually trying to understand the full SSO flow in regards to the SF proxy functionality for BTP CF extensions. See 830748/2021. 

Shouldn't we expect upon proxying that SF sends the name ID of the user being proxied to to the ACS of BTP + ACS of the approuter so that the new identity is propagated to the extension?

**Comment by ekaterina-mitova** [comment]
Hello @piejanssens,

The SSO setup is explained in the documentation. For further assistance and specific details, please continue the discussion in the opened ticket. 

Best regards, 
Ekaterina
