### ISSUE TITLE
Feedback for "Regions"

### ISSUE THREAD

**Issue by ExternalMe** [SAP-docs/btp-cloud-platform#6]
https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/350356d1dc314d3199dca15bd2ab9b0e.html?locale=en-US#standard-disaster-recovery

Hi, where can i get information about upcoming changes to the ip-ranges? Currently I am only getting push emails afterwards by watching this site: https://wiki.scn.sap.com/wiki/display/SAPHCP/Release+Highlights+for+SAP+Business+Technology+Platform.

Kind regards,

Christian.

**Comment by sdanter** [comment]
Hello Christian, 

thank you for your feedback, we are discussing this internally and will get back to you soon.

**Comment by sdanter** [comment]
Hello @ExternalMe,

there are two channels through which changes to the Regions information are announced: What's New Release Notes & the Cloud System Notification Subscriptions (CSNS) application which can be accessed through the Cloud Availability Center (CAC).

You mentioned that you are already subscribed to the release notes, so that area should be covered. You can also check the release notes manually for information related to Regions by heading to the [What's New Viewer](https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html) and filtering for the **Region** component.

If you want to also receive notifications through CAC/CSNS, you can subscribe to the **foundational services for SAP BTP** profile. You can find it using the **Cloud Service** filter in the CSNS application. For more information on CSNS, please refer to the User Guide [here](https://support.sap.com/content/dam/support/en_us/library/ssp/my-support/systems-installations/cac/csns_user_guide.pdf).

The official documentation will be updated to contain this information in the near future.

**Comment by nikolasimeonov77** [comment]
The following topic is updated and will be published with the next release: https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/99070c7bfc0e4f41842bd7c648b7fca7.html?version=Cloud.
