### ISSUE TITLE
Feedback for "Access UAA Admin APIs"

### ISSUE THREAD

**Issue by qmacro** [SAP-docs/btp-cloud-platform#90]
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html?locale=en-US&state=PRODUCTION&version=Cloud

In this section, there's a link missing entirely:

```
For more information, see .
```

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by MichaelPShea** [comment]
Hi DJ, I'm sorry, but I don't see the error. When I look on the Help Portal and when I look at the markdown version, the two places where the string "For more information" appears, it is followed by a link. You may have managed to catch the topic at a point in time when we were publishing and the link wasn't available. It appears that the problem has been fixed in the meantime. Thanks for your contribution!
